services:
  - type: web
    name: cibil-score-app
    env: python
    buildCommand: |
      echo "=== Installing Python packages ===" &&
      python -m pip install --upgrade pip setuptools wheel &&
      pip install --no-cache-dir -r requirements.txt &&
      echo "=== Building React frontend ===" &&
      cd Loan_Approval/project && 
      node --version &&
      npm --version &&
      npm install --legacy-peer-deps &&
      npm run build && 
      cd ../..
    startCommand: gunicorn --config gunicorn.conf.py app:app
    envVars:
      - key: FLASK_DEBUG
        value: "False"
      - key: PORT
        value: "5000"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      - key: NODE_VERSION
        value: "18.17.0" 